### ISSUE TITLE
Mass mock data of observations

### ISSUE THREAD

**Issue by pavel-ilin** [COVID-19-electronic-health-system/Coronalytics#10]
## Summary

[Original issue](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/392) in CoronaTracker repo.

- [ ] Create a mass amount of semi-structured data based off our observations currently being created here, and with any additional features @ngiangre may need.
- [ ] Create Rails API and generate mock data in see file
- [ ] Deploy Rails API on Heroku to make data accessible

## Motivation

While we won't be able to analyze real user data for some time, we want to start mocking data and seeing if we can get things working with OpenMined draw meaningful insights from the survey we're asking users

## Describe alternatives you've considered

Waiting until users start entering data (we don't have that luxury of guaranteed users)

## Additional context

Work closely with @ngiangre and the Analytics team to ensure data is created and structured to their specifications

**Comment by ngiangre** [comment]
Thanks for putting this issue here!

The mock data will be useful for getting the Analytics team started and building infrastructure. While I'm not convinced yet that the mock data will be in the exact form and at a location and extractable in the same way as with actual user data, the mock data will be a fantastic start to building our infrastructure and get us thinking more about our role in CoronaTracker.
